default:
  image: hub.docker.io/crcasis/curso_docker_infra


stages:
  - deploy
  - release

.build_job: &build_job
  - export VERSION=$CI_COMMIT_SHORT_SHA
  - export REGISTRY_IMAGE=$CI_REGISTRY_IMAGE
  - make build

.docker_login: &docker_login
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD hub.docker.io

build_and_deploy_image:
  stage: deploy
  script:
    - *docker_login
    - *build_job
    - make push
  only:
    - main

release_image:
  stage: release
  script:
    - *docker_login
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
